codecov:
  require_ci_to_pass: true
  branch: master

coverage:
  precision: 2
  round: down
  range: 70..80
  status:
    project:
      default:
        target: 80%
        threshold: 5%
        if_ci_failed: error

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no
